-- Even Fibonacci numbers

-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


main = do
    print (sum (filter even (fib_until 4000000)))

fib_until threshold = fib_from_index_until 0 threshold

fib_from_index_until :: Int -> Int -> [Int]
fib_from_index_until i threshold
    | fib_i < threshold = fib_i:(fib_from_index_until (i + 1) threshold)
    | otherwise = []
        where fib_i = fibonacci i

fibonacci :: Int -> Int
fibonacci 0 = 0
fibonacci 1 = 1
fibonacci 2 = 1
fibonacci x =  fibonacci (x - 1) + fibonacci (x - 2)
